### ISSUE TITLE
BUG - GitHub Enterprise Server Support

### ISSUE THREAD

**Issue by ArkShocer** [OP5dev/TF-via-PR#399]
#### Describe the bug

When using the action in a GitHub Enterprise Server Environment (github.yourcompany.com), the action cannot use the correct API via the GitHub CLI.  Same issue when used in the new GHE.com Instances. It does work as expected when I'm using it in an Github.com Enterprise

```yaml
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: OP5dev/TF-via-PR@v13
        with:
          # Run plan by default, or apply on merge with lock.
          working-directory: terraform/azure-infra
          command: ${{ github.event_name == 'push' && 'apply' || 'plan' }}
          arg-lock: ${{ github.event_name == 'push' }}
          arg-var-file: variables/dev.tfvars
```

#### To Reproduce

Run the action in a GitHub Enterprise Server

#### Expected behavior

No GitHub CLI API Issue from the action.

#### Screenshots

![Image](https://github.com/user-attachments/assets/bacedf48-117a-4f32-a1fd-b16a89a8b922)

#### Additional context

Looking through the `action.yml`, I couldn't find anything that the API uses the `gh auth login` command, so I guess it assumes it is always run on github.com and doesn't need an auth?. I can also provide more logs if needed (pure logs, no screenshot). Also want to point out that I really love this custom made solution! Covers our need perfectly, and no need to use atlantis/digger or some other terraform service which requires some maintenance!

**Comment by ArkShocer** [comment]
Thank you for the fast reply. I went ahead and already tried the suggestion. Setting `GH_HOST` alone resulted in the first error below

![Image](https://github.com/user-attachments/assets/c19e3190-5cf6-4e34-a303-fca5cbd116cb)

Adding `GH_ENTERPRISE_TOKEN` with enough permissions like this:
```yaml
  - uses: hashicorp/setup-terraform@v3
  - uses: OP5dev/TF-via-PR@v13
    with:
      working-directory: terraform/azure-infra
      command: ${{ github.event_name == 'push' && 'apply' || 'plan' }}
      arg-lock: ${{ github.event_name == 'push' }}
      arg-var-file: variables/dev.tfvars
      # validate: true
    env:
      GH_HOST: internal.example.com
      GH_ENTERPRISE_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}
```
results in a "better" response, as it goes and installs the providers but still errors out in the end :(

![Image](https://github.com/user-attachments/assets/2866a68f-cde8-4422-9ec5-78e0dbd33758)

Maybe it's an issue with the API path as the server uses `internal.example.com/api/v3` but also setting that as `GH_HOST` did not help. To me it looks like it can find some correct endpoints that are shared across cloud and server?

![Image](https://github.com/user-attachments/assets/f5d3e1f0-5cdc-4c27-9262-882a533046f5)

**Comment by rdhar** [comment]
Ah shoot, this might be a tad tricker than expected.

Just as a sanity check for me, can you confirm that you've replaced the "internal.example.com" with your actual internal/enterprise GitHub URL? I'm almost certain that you have, and the screenshot is obfuscated (including the "random-id-hash" tfplan), but wanted to double-check, just in case!

Assuming that's all kosher, I think you've hit it on the head when you say, "it looks like it can find some correct endpoints that are shared across cloud and server." I think it might because of defaults assumed by this Action which I'd missed at first. Specifically, `token` input:

```yaml
  - uses: op5dev/tf-via-pr@v13
    with:
      working-directory: terraform/azure-infra
      command: ${{ github.event_name == 'push' && 'apply' || 'plan' }}
      arg-lock: ${{ github.event_name == 'push' }}
      arg-var-file: variables/dev.tfvars
      token: ${{ secrets.GH_ENTERPRISE_TOKEN }} # <- this li'l stinker
    env:
      GH_HOST: internal.example.com
      GH_ENTERPRISE_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }} # <- might not be required then
```

Since `token: ${{ github.token }}` is set by default, it likely overrode the `GH_ENTERPRISE_TOKEN` environment variable. Lemme know how it works out!

**Comment by ArkShocer** [comment]
Yes, I can confirm I've replaced the `internal.example.com` with the actual domain (ghe.mycompany.com) of the GitHub Server instance. I've tried setting `token: ${{ secrets.GH_ENTERPRISE_TOKEN }}` and `token: ${{ secrets.GITHUB_TOKEN }}` both result in the same issue as before. I've noticed that if I don't set `env:  GH_ENTERPRISE_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}` at all, the error goes back to the first Image, so it looks like we are not on the wrong track so far.

**Comment by rdhar** [comment]
Just to humour me, what happens if you add the following `gh auth` step _before_ calling TF-via-PR? I'm curious if GH CLI authentication is transferred across workflow steps.

```yaml
- run: gh auth login --hostname ${{ env.GH_HOST }}
  env:
    GH_HOST: internal.example.com
    GH_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}
    GH_ENTERPRISE_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}

- uses: op5dev/tf-via-pr@v13
  with:
    working-directory: terraform/azure-infra
    command: ${{ github.event_name == 'push' && 'apply' || 'plan' }}
    arg-lock: ${{ github.event_name == 'push' }}
    arg-var-file: variables/dev.tfvars
    token: ${{ secrets.GH_ENTERPRISE_TOKEN }}
  env:
    GH_HOST: internal.example.com
    GH_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}
    GH_ENTERPRISE_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}
```

This configuration is definitely over-the-top, but I wanna see it working first before removing 1-line/variable at a time.

By the way, can you confirm the workflow job has the relevant permissions, and is compatible with GitHub Enterprise Server [2.20 and above](https://cli.github.com/manual/)? 

```yaml
permissions:
  actions: read # Required to identify workflow run.
  checks: write # Required to add status summary.
  contents: read # Required to checkout repository.
  id-token: write # Required to authenticate via OIDC.
  pull-requests: write # Required to add comment and label.
```

**Comment by ArkShocer** [comment]
Running the following;
```yaml
- run: gh auth login --hostname ${{ env.GH_HOST }}
  env:
    GH_HOST: internal.example.com
    GH_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}
    GH_ENTERPRISE_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}
```
Results in 

![Image](https://github.com/user-attachments/assets/c204ce94-1039-4555-8038-1e91647b86f9)

Removing `GH_ENTERPRISE_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}` results in a long run without any error as it waits for browser input, so I've aborted it. You also don't see which code it is until you abort the run.

![Image](https://github.com/user-attachments/assets/059aaab7-a4f0-4871-b88a-0d09b181bd76)

I've now added the `id-token: write` permission, still same issues. We are running at nearly the latest Server Version (3.15.1)

**Comment by rdhar** [comment]
Alright, interesting, that'd seem to indicate to me that the `gh auth login` approach is a lost-cause since it's only applicable for local-use, whereas the CI context of GH Actions requires token-based authentication.

If you haven't already, would you mind removing the `gh auth login` step altogether, then just trying TF-via-PR with all the `GH_` environment variables + `token` input like so:

```yaml
- uses: op5dev/tf-via-pr@v13
  with:
    working-directory: terraform/azure-infra
    command: ${{ github.event_name == 'push' && 'apply' || 'plan' }}
    arg-lock: ${{ github.event_name == 'push' }}
    arg-var-file: variables/dev.tfvars
    token: ${{ secrets.GH_ENTERPRISE_TOKEN }}
  env:
    GH_HOST: internal.example.com
    GH_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}
    GH_ENTERPRISE_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}
```

**Comment by ArkShocer** [comment]
Okay, some big progress as it finally progressed to actually running terraform plan successfully! Sadly, the next Issue arrived as some actions that are used are not supported on GHES apparently (see: https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new (`upload-artifact@v4+ is not currently supported on GHES yet. If you are on GHES, you must use v3.`)). I think it could also error out because some actions are locally cached with each version upgrade, which means it doesn't have the newest one from the cloud available. I can go into the Admin Config and delete the action cache so it uses the newest one from the cloud.

![Image](https://github.com/user-attachments/assets/8609f8b2-8863-4007-8b4e-05271c618a05)

Current working one as you suggested
```yaml
  - uses: OP5dev/TF-via-PR@v13
    with:
      # Run plan by default, or apply on merge with lock.
      working-directory: terraform/azure-infra
      command: plan
      arg-lock: ${{ github.event_name == 'push' }}
      arg-var-file: variables/dev.tfvars
      token: ${{ secrets.GH_ENTERPRISE_TOKEN }}
    env:
      GH_HOST: ghe.example.xyz
      GH_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}
      GH_ENTERPRISE_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}
```

**Comment by ArkShocer** [comment]
Guess v4 is not gonna be an Option https://github.com/github/roadmap/issues/930 :/

**Comment by rdhar** [comment]
Gah, so close, yet so far! 

</br>

> Current working one as you suggested

- I'd start by removing the `GH_TOKEN:` line as I don't think it's contributing anything at all.
- I'd try to see if it works with `token:` only or `GH_ENTERPRISE_TOKEN:` only, instead of both together.

</br>

> upload-artifact@v4+ is not currently supported on GHES yet

I can't believe that the one, the ONE, dependency I thought was safe due to 1st party/native support has let us down. How can GitHub deprecate v3 last year, _without_ updating support for GHE as well—ridiculous!

At this point, I don't think your GHE instance will be able to make any use of TF-via-PR since "actions/upload-artifact" is a core dependency (for storage/retrieval of plan file)

… The only other viable option I can see is to include conditional support for upload-artifact@v3, primarily for GHE users. Unless I'm way-off, I don't think it'd be _too_ involved to determine whether the Action is running within the context of a GHE and, if so, fallback on v3 instead of v4. 🤔

**Comment by rdhar** [comment]
Only _if_ you feel comfortable, could I request you to try PR #401 branch in order to validate support for GHE as follows:

```yaml
  - uses: op5dev/tf-via-pr@feat--ghe-support
    with:
      working-directory: terraform/azure-infra
      command: ${{ github.event_name == 'push' && 'apply' || 'plan' }}
      arg-lock: ${{ github.event_name == 'push' }}
      arg-var-file: variables/dev.tfvars
      token: ${{ secrets.GH_ENTERPRISE_TOKEN }}
    env:
      GH_ENTERPRISE_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}
```

Assuming that works, would you mind retrying but without `token` input, and again with `token` input but without `GH_ENTERPRISE_TOKEN` env?

Once the minimum-necessary config is established, we can cut a new release of TF-via-PR with built-in GHE support.

**Comment by ArkShocer** [comment]
Hey, so I've tested the new branch with both `token` and `GH_ENTERPRISE_TOKEN` and this time it was able to create an artifact! There is still an error showing up in the last part of the action.

![Image](https://github.com/user-attachments/assets/3cf6cba3-f535-4e42-b1bc-5c362fb16fe3)

**Comment by rdhar** [comment]
Terrific, looks like progress! Albeit, the lack of helpful error message is far from ideal. 

1. Was it at least able to create a PR comment?
2. Was it at least able to post on the workflow summary page?

The 403 error leads me to believe the last hurdle maybe related to the permissions granted to the GitHub token.

Would you mind retrying the PR branch as before, but without the `token` input to compare differences, if any?

**Comment by ArkShocer** [comment]
I've got an update. You writing `... maybe related to the permissions ...` gave me the Idea of trying the env `GH_ENTERPRISE_TOKEN` with the global `GITHUB_TOKEN` secret - and it worked! So using a custom PAT-Token as suggested here (https://github.com/cli/cli/issues/3522#issuecomment-881052634) from the issue you linked earlier was not entirely wrong. Setting the env `GH_TOKEN` with `${{ secrets.GITHUB_TOKEN }}` did nothing and gave me the same error I first encountered but with enterprise it worked. The PAT-Token {{ secrets.GH_ENTERPRISE_TOKEN }} would probably also work if I gave it more permissions.

Here is the full working yaml
```yaml
jobs:
  provision:
    runs-on: ubuntu-latest

    permissions:
      actions: read        # Required to identify workflow run.
      checks: write        # Required to add status summary.
      contents: read       # Required to checkout repository.
      pull-requests: write # Required to add comment and label.

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

    steps:     
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: OP5dev/TF-via-PR@feat--ghe-support
        with:
          # Run plan by default, or apply on merge with lock.
          working-directory: terraform/azure-infra
          command: plan
          arg-lock: ${{ github.event_name == 'push' }}
          arg-var-file: variables/dev.tfvars
        env:
          GH_ENTERPRISE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

![Image](https://github.com/user-attachments/assets/6794002b-78a6-42ce-8913-28c0e5f984a7)

I do still see an API issue as before I tested it without a PR but now with one I can see the following in the logs

![Image](https://github.com/user-attachments/assets/f5b9273f-2a5d-4c0f-a5b4-02ffdc25058f)

The API did set a label on the PR, guess it has an Issue with getting it again because it does not exist on the org-level bot on repo-level?

![Image](https://github.com/user-attachments/assets/d17a460c-c0c8-466c-a2d4-82b0d92793e0)

**Comment by ArkShocer** [comment]
I've got an update. You writing ... maybe related to the permissions ... gave me the Idea of trying the env GH_ENTERPRISE_TOKEN with the global GITHUB_TOKEN secret - and it worked! So using a custom PAT-Token as suggested here (https://github.com/cli/cli/issues/3522#issuecomment-881052634) from the issue you linked earlier was not entirely wrong. Setting the env GH_TOKEN with ${{ secrets.GITHUB_TOKEN }} did nothing and gave me the same error I first encountered but with enterprise it worked. The PAT-Token {{ secrets.GH_ENTERPRISE_TOKEN }} would probably also work if I gave it more permissions.

Here is the full working yaml
```yaml
jobs:
  provision:
    runs-on: ubuntu-latest

    permissions:
      actions: read        # Required to identify workflow run.
      checks: write        # Required to add status summary.
      contents: read       # Required to checkout repository.
      pull-requests: write # Required to add comment and label.

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

    steps:     
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: OP5dev/TF-via-PR@feat--ghe-support
        with:
          # Run plan by default, or apply on merge with lock.
          working-directory: terraform/azure-infra
          command: plan
          arg-lock: ${{ github.event_name == 'push' }}
          arg-var-file: variables/dev.tfvars
        env:
          GH_ENTERPRISE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
````

![Image](https://github.com/user-attachments/assets/943de83c-c070-4758-971f-f3ef3d261f7b)


I do still see an API issue as before I tested it without a PR but now with one I can see the following in the logs

![Image](https://github.com/user-attachments/assets/a3ca0105-3318-4e6f-a32e-05ab4f01c6d3)

The API did set a label on the PR, guess it has an Issue with getting it again because it does not exist on the org-level bot on repo-level?

![Image](https://github.com/user-attachments/assets/98fac2e6-116d-4ab8-85a6-cef9ab825354)
