### ISSUE TITLE
GHA Workflow example for "apply" from PR before merge

### ISSUE THREAD

**Issue by ruzickap** [OP5dev/TF-via-PR#402]
#### Describe the solution you'd like

I have one more use-case for the `examples` directory:

* I’d like an example of a GitHub Workflow that allows me to manually run `apply` from a PR.

Why?

In the past, I made many mistakes in TF code changes that only became apparent during `apply`.
If such code is in a PR (where `plan` won’t help detect these issues) and I merge it into the `main` branch, I end up with "incorrect code" in `main`, requiring an urgent fix.

On the other hand, if I can run `apply` while working on a PR (before merging), I can catch any issues early and fix them as part of the PR.

**Comment by rdhar** [comment]
Hey @ruzickap, good shout! Would you mind expanding on the use-case in a bit more detail, in order to inform what the example workflow should look like? 

For example, I'm totally with you on wanting to run `apply` on the PR branch before merge. But how exactly do you intend to trigger `apply`? From anecdotal experience, I'd suggest leveraging PR labels. In other words, adding a "tf-apply" would trigger an `apply`.

Why a PR label instead of, say, a PR comment? As easy as it would be to use a PR comment like "/apply" as a trigger event, unfortunately PR comment trigger is filed under [`issue_comment`](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#issue_comment) event, which is woefully limited compared to the equivalent [`pull_request`](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request) event trigger.

Since PR labels fall under `pull_request` > `labeled` event, this allows to be creative with workflow logic. While we have an example workflow for "tf-plan" label already (see here), I can expand it out to include "tf-apply" equivalent as well. How does that sound?

**Comment by ruzickap** [comment]
Thank you for the great description. 
I like the idea of using PR labels, but I'm not convinced it's the right approach.

For example, I have a pull request (PR) ready that I would like to merge, but I want to run `apply` first:

1. I use the `tf-apply` label.
1. When I run `apply`, it reveals some code errors.
1. I update the PR and fix the problem.
1. Next, I need to remove the `tf-apply` label.
1. Finally, I add the `tf-apply` label again.
1. ...

In short - step 4) and 5) are not very user friendly because people need to remove and add labels to trigger the action.

The "ChatOps" like `/apply` sounds easier / more user friendly.

Another option can be using using `workflow_dispatch`:

```yaml
on:
  workflow_dispatch:
    inputs:
      terraform_action:
        type: choice
        description: Terraform action
        default: plan
        required: true
        options:
          - plan
          - apply
          - plan -destroy
          - destroy
          - destroy -lock=false
      env-variables:
        description: Environment variable(s)
        # 'TF_CLI_ARGS_destroy=-auto-approve -lock=false'
        default: "'TF_LOG=ERROR' 'TF_DATA_DIR=.terraform'"
        required: false
```

Screenshots:

![Image](https://github.com/user-attachments/assets/20090ffd-41c6-4a37-be8c-483c7229628c)

![Image](https://github.com/user-attachments/assets/2dbd229b-be59-4d79-a8fa-39f6e500e7a2)

I'm not sure which one is the best option...
