### ISSUE TITLE
Version 13.1.3 failure

### ISSUE THREAD

**Issue by santipov-fl** [OP5dev/TF-via-PR#424]
#### Describe the bug

```
jq: error: tf/0 is not defined at <top-level>, line 1:
(.jobs[] | select((.name | ascii_downcase | gsub("-|_"; " ")) == (tf | ascii_downcase | gsub("-|_"; " "))) | .id) // .jobs[0].id                                                                  
jq: 1 compile error
```

Configuration is simple
```
   - name: Terraform Plan
      uses: devsectop/tf-via-pr@v13
      with:
        command: 'plan'
        arg-lock: ${{ inputs.lock != '' && inputs.lock }}
        arg-var-file: secrets.tfvars
        working-directory: infra/terraform
        plan-encrypt: ${{ secrets.PASSPHRASE }}
        label-pr: false
        comment-pr: never
```
#### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. Observe error
