### ISSUE TITLE
Label-PR is not working as expected.

### ISSUE THREAD

**Issue by parthrspl** [OP5dev/TF-via-PR#439]
#### Describe the bug

During the Step: Label PR, it is not working as expected. 
It gives error : 
```
gh: Invalid request.

No subschema in "anyOf" matched.
For 'anyOf/0', {"labels[]" => "tf:plan"} is not an array.
For 'anyOf/1', {"labels[]" => "tf:plan"} is not an array.
"labels[]" is not a permitted key.
"labels" wasn't supplied. (HTTP 422)
{"message":"Invalid request.\n\nNo subschema in \"anyOf\" matched.\nFor 'anyOf/0', {\"labels[]\" => \"tf:plan\"} is not an array.\nFor 'anyOf/1', {\"labels[]\" => \"tf:plan\"} is not an array.\n\"labels[]\" is not a permitted key.\n\"labels\" wasn't supplied.","documentation_url":"https://docs.github.com/rest/issues/labels#add-labels-to-an-issue","status":"422"}
```

The Issue seems to be with form fields syntax of label for :  'anyOf/0', {"labels[]" => "tf:plan"} is not an array

#### To Reproduce

```
uses: op5dev/tf-via-pr@v13.1.5
with:
          working-directory: ${{ env.TERRAFORM_DIR }}
          arg-recursive: false
          arg-lock: false
          arg-get: true
          command: plan
```

#### Expected behavior

PR label should be updated with tf:plan
with proper JSON array (["tf:plan"]) 

##### Screenshot

![Image](https://github.com/user-attachments/assets/bbdc07e1-a9b3-4dfe-ab33-4124fa37ec05)
