### ISSUE TITLE
Using a nested strategy.matrix

### ISSUE THREAD

**Issue by cornerman** [OP5dev/TF-via-PR#440]
#### Describe the bug

Just after upgrading the action from version `11` to version `13`, I got an error concerning the action matrix.

#### To Reproduce

Use matrix like this:
```
    strategy:
      fail-fast: false # we never want to cancel a terraform call, it can lead to inconsistent terraform state.
      matrix:
        module:
          - directory: ./module1
          - directory: ./module2

    steps:
      ...
```

Running the github action leads to the following error:
```
   # Get the step number that has status "in_progress" from the current job.
  workflow_step=$(echo "$workflow_run" | jq --raw-output --arg job_id "$job_id" '.jobs[] | select(.id == ($job_id | tonumber)) | .steps[] | select(.status == "in_progress") | .number')
  echo "step=$workflow_step" >> "$GITHUB_OUTPUT"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
     ...
     GH_MATRIX: {
    "module": {
      "directory": "./deploy-roles"
    }
  }
jq: error (at <stdin>:5): string ("") and object ({"directory...) cannot be added
```

My workaround was now to flatten the matrix like this:
```
      matrix:
        module:
          - ./module1
          - ./module2
```

#### Expected behavior

It should work as usual

**Comment by rdhar** [comment]
Hi @cornerman, thanks for raising!

Since that's a major version upgrade, several inputs have changed. Could you share an obfuscated snippet of your workflow file, specifically the TF-via-PR step?

**Comment by cornerman** [comment]
@rdhar Yes, of course. Here is the complete workflow:

```
name: Terraform plan (PR) and apply (main)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tf:
    runs-on: ubuntu-24.04

    permissions:
      actions: read # Required to download repository artifact.
      checks: write # Required to add status summary.
      contents: read # Required to checkout repository.
      id-token: write # Required to authenticate via OIDC.
      pull-requests: write # Required to add PR comment and label.

    timeout-minutes: 60
    concurrency: "terraform-${{ matrix.module.directory }}" # terraform operations for the same module should not be concurrent

    strategy:
      fail-fast: false # we never want to cancel a terraform call, it can lead to inconsistent terraform state.
      matrix:
        module:
          - directory: ./module1
          - directory: ./module1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create cache
        run: |
          mkdir --parents $HOME/.terraform.d/plugin-cache
          echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >> $GITHUB_ENV

      - name: Cache TF
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: cache-tf-${{ runner.os }}-${{ hashFiles('${{ matrix.module.directory }}/.terraform.lock.hcl') }}

      - name: Authenticate AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}

      - name: Setup TF
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.7"

      - name: Provision TF
        uses: devsectop/tf-via-pr@v13
        with:
          command: ${{ github.event_name == 'push' && 'apply' || 'plan' }}
          arg-chdir: ${{ matrix.module.directory }}
          arg-check: true
          validate: true
          format: true
```
