### ISSUE TITLE
Got Error 400  Error job is already completed

### ISSUE THREAD

**Issue by exodia0x** [OP5dev/TF-via-PR#455]
I just run Terraform Github Action via auth OIDC Azure Manage Identity when terraform plan is no problem but when i merge for apply got error. Did anyone have a problem like this or please give me an how to make it work.
```
Error: building account: could not acquire access token to parse claims: githubAssertion: received HTTP status 400 with response: {"source":"actions-run-service","statusCode":400,"errorMessage":"job is already completed"}
```

![Image](https://github.com/user-attachments/assets/ad8b7276-ea32-412e-b0c8-8981b2c6171c)

Here is my Github workflow
```yaml
---
name: Terraform CICD Deploy

on:
  pull_request:
  push:
    branches: 
    - main
    paths:
    - Environment/**

permissions:
  actions: read        # Required to identify workflow run.
  checks: write        # Required to add status summary.
  contents: read       # Required to checkout repository.
  pull-requests: write # Required to add comment and label.
  issues: write        # Required to create new label.
  id-token: write      # create OpenID Connect (OIDC) ID token

jobs:

  Check_Environment_Change:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Filter Directory Change
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            DEV:
              - 'Environment/DEV/**'
    outputs:
      changes_dev: ${{ steps.changes.outputs.DEV }}

  Provision_Environment_DEV:
    needs: Check_Environment_Change
    if: ${{ needs.Check_Environment_Change.outputs.changes_dev == 'true' }}
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Setup GitHub ACCESS_TOKEN with global configuration
        run: |
          git config --global url."https://tarathec:${{ secrets.REPO_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Terraform Variables
        run: |
          echo "TF_VAR_use_oidc=true" >> $GITHUB_ENV
          echo "TF_VAR_oidc_request_token=$ACTIONS_ID_TOKEN_REQUEST_TOKEN" >> $GITHUB_ENV
          echo "TF_VAR_oidc_request_url=$ACTIONS_ID_TOKEN_REQUEST_URL" >> $GITHUB_ENV
          echo "ARM_USE_MSI=true" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: "Setup: Log in with Azure"
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "list 1"
        run: |
          ls -al ~/.terraform.d/plugin-cache

      - name: "list 2"
        run: |
          ls -al

      - name: Init TF
        id: tf
        if: ${{ github.event_name == 'pull_request' }}
        uses: op5dev/tf-via-pr@v13
        with:
          # working-directory: Environment/DEV
          command: init
          arg-lock: false
          format: true
          validate: true
          arg-var-file: Environment/DEV/main.tfvars
          arg-backend-config: Environment/DEV/cloudflarer2.tfbackend

      - name: Setup TFLint
        if: ${{ github.event_name == 'pull_request' }}
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_wrapper: true

      - name: Run TFLint
        id: tflint
        if: ${{ github.event_name == 'pull_request' }}
        # working-directory: Environment/DEV
        run: |
          tflint --init
          tflint --format compact
        continue-on-error: true

      - name: Comment if TFLint errors
        if: ${{ github.event_name == 'pull_request' && steps.tflint.outputs.exitcode != 0 }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Compose TFLint output.
          tflint='${{ steps.tflint.outputs.stderr || steps.tflint.outputs.stdout }}'
          tflint="<details><summary>TFLint error.</summary>

          \`\`\`hcl
          $(echo "$tflint" | sed 's/`/\\`/g')
          \`\`\`
          </details>"

          # Get body of PR comment from tf step output.
          comment=$(gh api /repos/{owner}/{repo}/issues/comments/${{ steps.tf.outputs.comment-id }} --method GET --jq '.body')

          # Replace placeholder with TFLint output.
          comment="${comment//<!-- placeholder-2 -->/$tflint}"

          # Update PR comment combined with TFLint output.
          gh api /repos/{owner}/{repo}/issues/comments/${{ steps.tf.outputs.comment-id }} --method PATCH --field body="$comment"

          # Exit workflow due to TFLint error.
          exit 1
          
      # Run plan by default, or apply on merge.
      - name: Provision TF
        uses: op5dev/tf-via-pr@v13
        with:
          # working-directory: Environment/DEV
          command: ${{ github.event_name == 'push' && 'apply' || 'plan' }}
          arg-lock: ${{ github.event_name == 'push' }}
          arg-var-file: Environment/DEV/main.tfvars
          arg-backend-config: Environment/DEV/cloudflarer2.tfbackend
          arg-workspace: dev

      - name: "list 3"
        run: |
          ls -al ~/.terraform.d/plugin-cache

      - name: "list 4"
        run: |
          ls -al
```
